

###
POST http://127.0.0.1:8000/api/route/
Content-Type: application/json

{
    "start": "Austin, TX",
    "end": "Detroit, MI"
}

###
GET http://localhost:8000/api/route/view-map/?start=Austin, TX&end=Detroit, MI